---
title: "Explore Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(knitr)
library(shiny)
library(crosstalk)
library(DT)
library(plotly)
library(scales)
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=F)
testdata <- read.csv("EloDashData.csv")
testdata <- testdata[,-1]
testdata$Date<-as.Date(testdata$Date,format="%Y-%m-%d")
testdata$Year <- as.character(testdata$Year)
tdata <- SharedData$new(testdata)
rank <- read.csv("EloRank25.csv")
rank <- rank[,-1]
```


Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
filter_select("Name", "Choose Player", tdata, ~Name)
```

```{r}
filter_select("Year", "Choose Year", tdata, ~Year)
```


Column {data-width=400}
-----------------------------------------------------------------------

### Table of Elo Ratings

```{r}
datatable(tdata,
          class = "compact cell-border",
          rownames = FALSE,
          options = list(order = list(1, "desc"),
                         autoWidth = FALSE,
                         pageLength = 20))
```

Column {data-width=600}
-----------------------------------------------------------------------

### Plot of Top-25 Players Over Time

```{r}
g <- ggplot(tdata,aes(as.Date(Date),Elo,group=Name)) + 
  geom_line(aes(color=Name)) +
  scale_x_date(date_labels = "%Y")+
  xlab("Date")

ggplotly(g,tooltip = c("x", "y", "group"))%>%
    layout(showlegend = F)
```


###